"""Bounded Strands + Bedrock strategy selector for Adaptive Stay Gate H.

The model never authors device commands, strategy primitives, Dream verdicts, approval,
or activation. It may only select opaque option references from the catalog generated by
deterministic code for the current stay.
"""
from dataclasses import dataclass
from datetime import datetime, timezone
import importlib.metadata
import json
import re
import time

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .audit import digest
from .stay_dream import StrategyCatalog, StrategyOption


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class OptionSelectionData(_Strict):
    option_refs: list[str] = Field(min_length=1, max_length=6)


@dataclass(frozen=True)
class PlannerResult:
    options: tuple
    provenance: dict

    def __post_init__(self):
        if type(self.options) is not tuple or any(type(v) is not StrategyOption for v in self.options):
            raise ValueError("typed selected options required")
        if type(self.provenance) is not dict:
            raise ValueError("planner provenance required")


def validate_selection(raw, catalog):
    if type(catalog) is not StrategyCatalog:
        raise ValueError("typed StrategyCatalog required")
    data = OptionSelectionData.model_validate(raw).model_dump()
    refs = tuple(data["option_refs"])
    if len(refs) != len(set(refs)):
        raise ValueError("duplicate strategy option reference")
    known = {option.option_ref: option for option in catalog.options}
    if any(ref not in known for ref in refs):
        raise ValueError("unknown strategy option reference")
    return tuple(known[ref] for ref in refs)


def _conflict_view(assessment):
    return tuple({
        "code": c.code,
        "resource_type": c.resource_type,
        "resource_id": c.resource_id,
        "requested_values": c.requested_values,
    } for c in assessment.conflicts)


_SYSTEM = """You are the bounded planning specialist inside Adaptive Stay.
Alexa+ is the customer-facing conversational agent. You are not Alexa+.
You must call discover_stay_strategies before submitting output.
The tool returns the complete option catalog for this exact stay. Select only existing
opaque option_ref values. Never invent a device, capability, room, zone, command, value,
option, verdict, score, approval, activation, or safety claim.
You do not grade options. Deterministic Dream will evaluate them after you return.
If six or fewer options exist, select all options so Dream can test the full bounded set.
If more than six exist, select up to six diverse options spanning materially different
primitive combinations. Return structured output only."""


class LivePlannerFailure(RuntimeError):
    def __init__(self, diagnostic):
        self.diagnostic = dict(diagnostic)
        super().__init__(self.diagnostic.get("error", "LIVE_PLANNER_FAILED"))


# Gate J2 identity gate. Exactly two AWS identities may ever drive a real,
# billable Bedrock invocation from LiveStayPlanner: the pinned local
# development IAM user, and the pinned ECS task role's assumed-role identity
# (session name varies per task, everything else about the role is fixed).
# The account id and role name are literals in source, not environment- or
# config-supplied, so a misconfigured deploy cannot silently widen who is
# allowed to trigger real model calls from the public deployment. No other
# account, no other role name, and no root/unrelated IAM identity is ever
# accepted -- this deliberately stays a two-entry allowlist, not a pattern
# that matches "any role" or "any account".
_AUTHORIZED_ACCOUNT_ID = "861276109104"
_AUTHORIZED_DEV_USER_ARN = f"arn:aws:iam::{_AUTHORIZED_ACCOUNT_ID}:user/agent-factory-dev"
_AUTHORIZED_ECS_TASK_ROLE_NAME = "adaptive-stay-task-role"
_AUTHORIZED_ECS_ROLE_ARN_RE = re.compile(
    r"arn:aws:sts::" + _AUTHORIZED_ACCOUNT_ID
    + r":assumed-role/" + re.escape(_AUTHORIZED_ECS_TASK_ROLE_NAME)
    + r"/[^/]+"
)


def is_authorized_runtime_identity(arn):
    """True only for the pinned dev IAM user or the pinned ECS task role's
    assumed-role identity in the pinned account. Anything else -- a wrong
    account, a wrong/renamed role, the account root user, an unrelated IAM
    user or role, a malformed or empty value -- returns False.
    """
    if not isinstance(arn, str) or not arn:
        return False
    if arn == _AUTHORIZED_DEV_USER_ARN:
        return True
    return _AUTHORIZED_ECS_ROLE_ARN_RE.fullmatch(arn) is not None


class LiveStayPlanner:
    kind = "LIVE"

    def __init__(self, profile_name="agent-factory", region="us-east-1",
                 model_id="amazon.nova-pro-v1:0"):
        self.profile_name = profile_name
        self.region = region
        self.model_id = model_id

    def plan(self, catalog, assessment):
        if type(catalog) is not StrategyCatalog:
            raise ValueError("typed StrategyCatalog required")
        if not catalog.options:
            raise ValueError("strategy options required for live planning")

        import boto3
        from botocore.config import Config
        from botocore.exceptions import ProfileNotFound
        from strands import Agent, tool
        from strands.models import BedrockModel

        stage = "aws_identity"
        calls = []
        grounding = []
        start = time.perf_counter()
        try:
            config = Config(connect_timeout=5, read_timeout=25, retries={"total_max_attempts": 1})
            try:
                session = boto3.Session(profile_name=self.profile_name, region_name=self.region)
                identity = session.client("sts", config=config).get_caller_identity()
            except ProfileNotFound:
                # No local named CLI profile exists in this runtime -- this is
                # the normal, expected case on an ECS task, which authenticates
                # via its task role through the default credential provider
                # chain (container credentials) rather than a profile file.
                # Falling back here changes nothing about *which* identities
                # are trusted: the same is_authorized_runtime_identity() gate
                # below still runs against whatever identity this resolves to.
                session = boto3.Session(region_name=self.region)
                identity = session.client("sts", config=config).get_caller_identity()
            arn = identity.get("Arn", "")
            if not is_authorized_runtime_identity(arn):
                raise LivePlannerFailure({
                    "error": "LIVE_PLANNER_FAILED",
                    "failure_stage": "aws_identity",
                    "error_type": "UnexpectedDevelopmentIdentity",
                })

            stage = "strands_setup"
            model = BedrockModel(
                boto_session=session,
                boto_client_config=config,
                model_id=self.model_id,
                temperature=0,
                max_tokens=1200,
                streaming=False,
            )

            def after(parsed, **kwargs):
                meta = parsed.get("ResponseMetadata", {})
                calls.append({
                    "http_status": meta.get("HTTPStatusCode"),
                    "request_id": meta.get("RequestId"),
                })

            model.client.meta.events.register(
                "after-call.bedrock-runtime.Converse", after
            )

            @tool
            def discover_stay_strategies() -> dict:
                """Return the complete bounded option catalog and current physical conflicts."""
                grounding.append("discover_stay_strategies")
                return {
                    "conflicts": _conflict_view(assessment),
                    "strategy_catalog": catalog.public_view(),
                }

            class GroundedSelection(OptionSelectionData):
                @model_validator(mode="after")
                def grounded(self):
                    if not grounding:
                        raise ValueError("discover_stay_strategies must be called first")
                    validate_selection(self.model_dump(), catalog)
                    if len(catalog.options) <= 6:
                        expected = {option.option_ref for option in catalog.options}
                        if set(self.option_refs) != expected:
                            raise ValueError("small bounded catalog requires complete option coverage")
                    return self

            agent = Agent(
                model=model,
                tools=[discover_stay_strategies],
                system_prompt=_SYSTEM,
                structured_output_model=GroundedSelection,
                callback_handler=None,
                load_tools_from_directory=False,
                retry_strategy=None,
            )

            stage = "strands_tool_loop"
            result = agent(json.dumps({
                "task": "Select bounded strategy options for deterministic Dream evaluation.",
                "catalog_hash": catalog.catalog_hash,
            }))
            if result.structured_output is None:
                raise LivePlannerFailure({
                    "error": "LIVE_PLANNER_FAILED",
                    "failure_stage": "structured_output_missing",
                    "error_type": "StructuredOutputMissing",
                })

            selected = validate_selection(result.structured_output.model_dump(), catalog)
            if not calls or any(c.get("http_status") != 200 for c in calls):
                raise LivePlannerFailure({
                    "error": "LIVE_PLANNER_FAILED",
                    "failure_stage": "bedrock_invoke",
                    "error_type": "BedrockResponseNotSuccessful",
                })

            provenance = {
                "kind": "LIVE",
                "provider": "Strands / Amazon Bedrock",
                "model": self.model_id,
                "region": self.region,
                "profile": self.profile_name,
                "strands_version": importlib.metadata.version("strands-agents"),
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "latency_seconds": time.perf_counter() - start,
                "success": True,
                "bedrock_calls": calls,
                "grounding_calls": tuple(grounding),
                "input_hash": digest((catalog.catalog_hash, _conflict_view(assessment))),
                "output_hash": digest(tuple(o.option_ref for o in selected)),
                "credentials_recorded": False,
                "authoritative_verdict": False,
            }
            return PlannerResult(selected, provenance)
        except LivePlannerFailure:
            raise
        except Exception as exc:
            raise LivePlannerFailure({
                "error": "LIVE_PLANNER_FAILED",
                "failure_stage": stage,
                "error_type": type(exc).__name__,
            }) from None
